version: "3.9"
services:
  backend:
    container_name: nestjs-output-first-crud
    build: .
    tty: true
    depends_on:
      - db
    volumes:
      - .:/backend
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    environment:
      TZ: Asia/Tokyo # タイムゾーンを日本時刻に設定
    ports:
      - 8080:3000
    security_opt:
      - seccomp:unconfined
    # command: sh -c 'npm install && npm run start:dev'

  db:
    container_name: nestjs-output-first-db
    environment:
      - MYSQL_DATABASE=NEXTJS_OUTPUT_WITH_CRUD_DB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - nestjs-output-first-db:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306

volumes:
  nestjs-output-first-db:
  backend:
